### ISSUE TITLE
hidden files won't be taken care of

### ISSUE THREAD

**Issue by Andimeo** [wlixcc/SFTP-Deploy-Action#59]
In the local path, if there are files starting with a dot, like .env, it will not be passed to the remote folder.

**Comment by thegreenonion** [comment]
Is there until today any fix for that? Having the same issue with .env

**Comment by N0edL** [comment]
Yeah please add exclude or something thanks :)

**Comment by wlixcc** [comment]
Thank you for bringing up this issue! 🚀

### ✅ **Regarding Hidden Files and SFTP Uploads**

By default:
- If you use `local_path: './*'`, it **will not include hidden files** (e.g., `.gitignore`, `.env`, `.htaccess`).
- If you want to **include hidden files**, you should set `local_path` to `./` instead of `./*`.

---

### 🛠️ **Solution: Include Hidden Files**

Update your workflow configuration as follows:

```yaml
- name: Deploy with hidden files
  uses: wlixcc/SFTP-Deploy-Action@v1.2.5
  with:
    username: 'root'
    server: 'your.server.ip'
    ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    local_path: './'
    remote_path: '/var/www/app'
    rsyncArgs: '--exclude=node_modules --exclude=*.log'
    sftpArgs: '-o ConnectTimeout=5'
